### ISSUE TITLE
Mysql bug in full load with DMS

### ISSUE THREAD

**Issue by aroca** [awsdocs/aws-dms-user-guide#11] opened 2018-11-23 13:05 UTC
This bug causes that not all data being loaded to the target database.

The solution is to add an ECA.

If you ok guys, I will add this to the Mysql troubleshooting section.

Cheers!

**Comment by aroca** [comment] 2018-11-27 19:22
Ping fellows. Just to know if its ok to create a PR for this.

**Comment by hpaknia** [comment] 2019-05-20 19:16
I am experiencing this issue. Only 48,000 rows of 76,000 rows in the target are migrated to the destination. I am not sure if it is related to the bug you are reporting. 
Any updates on this? Can you explain the root cause? Any workarounds?

**Comment by joshbean** [comment] 2023-06-15 20:58
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).

**Closed as completed by joshbean** 2023-06-15 20:58 UTC
Labels: archived
